fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # use the ref you want to point at
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version. run `uv self update` and match it
    rev: 0.6.1
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # ruff version
    rev: v0.9.6
    hooks:
      # run the linter
      - id: ruff
        args: [ --fix ]
      # run the formatter
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    # pyright-python version
    rev: v1.1.394
    hooks:
      - id: pyright
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: uv.lock
